stages:
  split_data:
    cmd: python pipelines/bin/split_data.py
    deps:
    - ${paths.data.raw}
    - pipelines/bin/split_data.py
    - utils
    params:
    - split_data.valid_size
    - split_data.test_size
    - split_data.random_state
    outs:
    - ${paths.data.splitted}
  clean:
    cmd: python pipelines/bin/clean_data.py
    deps:
    - ${paths.data.splitted}
    - pipelines/bin/clean_data.py
    - utils
    outs:
    - ${paths.data.clean}
    - ${paths.pipelines.serialized}/data_cleaner.pkl
  transform_numerical_columns:
    cmd: python pipelines/bin/transform_numerical_columns.py
    deps:
    - ${paths.data.clean}
    - pipelines/bin/transform_numerical_columns.py
    - utils
    outs:
    - ${paths.data.transformed_numerical_columns}
    - ${paths.pipelines.serialized}/numerical_columns_transformer.pkl
  balance_data:
    cmd: python pipelines/bin/balance_data.py
    deps:
    - ${paths.data.transformed_numerical_columns}
    - pipelines/bin/balance_data.py
    - pipelines/lib/data_balance
    - utils
    params:
    - balance_data.method
    outs:
    - ${paths.data.balanced}
  transform_categorical_columns:
    cmd: python pipelines/bin/transform_categorical_columns.py
    deps:
    - ${paths.data.balanced}
    - pipelines/bin/transform_categorical_columns.py
    - utils
    params:
    - category_embedding
    - transform_categorical_columns.method
    outs:
    - ${paths.data.transformed_categorical_columns}
    - ${paths.pipelines.serialized}/categorical_columns_transformer.pkl
  reduce_data:
    cmd: python pipelines/bin/reduce_data.py
    deps:
    - pipelines/bin/reduce_data.py
    - ${paths.data.transformed_categorical_columns}
    - utils
    params:
    - frufs
    - rfe
    - reduce_data.method
    outs:
    - ${paths.data.reduced}
    - ${paths.pipelines.serialized}/data_reductor.pkl
  train_model:
    cmd: python models/bin/train_model.py
    deps:
    - ${train_model.study_input_path}
    - models/bin/train_model.py
    - utils
    params:
    - train_model
    outs:
    - ${paths.models.serialized}/${train_model.model_name}.pkl
    - ${paths.models.parameters}/${train_model.model_name}.json
  train_gaussian_nb:
    cmd: python models/custom_train/train_gaussian_nb.py
    deps:
    - models/custom_train/train_gaussian_nb.py
    - utils
    outs:
    - ${paths.models.serialized}/gaussian_nb.pkl
  train_lda:
    cmd: python models/custom_train/train_lda.py
    deps:
    - models/custom_train/train_lda.py
    - utils
    outs:
    - ${paths.models.serialized}/lda.pkl
  train_neural_network:
    cmd: python models/custom_train/train_neural_network.py
    deps:
    - models/custom_train/train_neural_network.py
    - utils
    outs:
    - ${paths.models.serialized}/neural_network.pkl
  calibrate_model:
    cmd: python models/bin/calibrate_model.py
    deps:
    - ${paths.models.serialized}/xgboost.pkl
    - models/bin/calibrate_model.py
    - utils
    params:
    - calibrate_model
    outs:
    - ${paths.models.serialized}/xgboost_calibrated.pkl