stages:
  split_data:
    cmd: python pipelines/bin/split_data.py
    deps:
    - ${paths.data.raw}
    - pipelines/bin/split_data.py
    - utils
    params:
    - split_data.valid_size
    - split_data.test_size
    outs:
    - ${paths.data.splitted}
  clean:
    cmd: python pipelines/bin/clean_data.py --validate
    deps:
    - ${paths.data.splitted}
    - pipelines/bin/clean_data.py
    - utils
    outs:
    - ${paths.data.clean}
    - ${paths.pipelines.serialized}/clean_data.pkl
  numerical_transformations:
    cmd: python pipelines/bin/numerical_transformations.py --validate
    deps:
    - ${paths.data.clean}
    - pipelines/bin/numerical_transformations.py
    - utils
    outs:
    - ${paths.data.numerical_transformed}
    - ${paths.pipelines.serialized}/numerical_transformations.pkl
  one_hot:
    cmd: python pipelines/bin/one_hot.py --validate
    deps:
    - ${paths.data.numerical_transformed}
    - pipelines/bin/one_hot.py
    - utils
    outs:
    - ${paths.data.categorical_transformed}
    - ${paths.pipelines.serialized}/one_hot.pkl
  category_embedding:
    cmd: python pipelines/bin/category_embedding.py --validate
    deps:
    - ${paths.data.numerical_transformed}
    - pipelines/bin/category_embedding.py
    - utils
    params:
    - category_embedding.embedder_n_epochs
    - category_embedding.embedder_num_layers
    outs:
    - ${paths.data.categorical_embedded}
    - ${paths.pipelines.serialized}/category_embedding.pkl
  frufs:
    cmd: python pipelines/bin/frufs.py --validate
    deps:
    - ${paths.data.categorical_transformed}
    - ${paths.data.categorical_embedded}
    - pipelines/bin/frufs.py
    - utils
    params:
    - frufs.output_n_cols
    - frufs.input
    outs:
    - ${paths.data.reduced}
    - ${paths.pipelines.serialized}/frufs.pkl
  smote:
    cmd: python pipelines/bin/smote.py
    deps:
    - ${paths.data.reduced}
    - pipelines/bin/smote.py
    - utils
    params:
    - smote.calibration_size
    outs:
    - ${paths.data.balanced_smote}
  oversample:
    cmd: python pipelines/bin/oversample.py
    deps:
    - ${paths.data.reduced}
    - pipelines/bin/oversample.py
    - utils
    params:
    - oversample.calibration_size
    outs:
    - ${paths.data.balanced}
