paths:
  data:
    raw: "resources/data/raw"
    splitted: "resources/data/splitted"
    clean: "resources/data/clean"
    transformed_numerical_columns: "resources/data/transformed_numerical_columns"
    balanced: "resources/data/balanced"
    transformed_categorical_columns: "resources/data/categorical_transformed"
    reduced: "resources/data/reduced"
  pipelines:
    serialized: "resources/pipelines/serialized"
  models:
    serialized: "resources/models/serialized"
    parameters: "resources/models/parameters"
    optuna_studies: "resources/models/studies"

split_data:
  random_state: 42
  test_size: 0.15
  valid_size: 0.15

balance_data:
  method: "passthrough"

transform_categorical_columns:
  method: "one_hot"


category_embedding:
  embedder_n_epochs: 5
  embedder_num_layers: 2

reduce_data:
  method: "rfe"

frufs:
  output_n_cols: 200

rfe:
  output_n_cols: 200

train_model:
  study_input_path: "resources/models/studies/xgboost/xgboost-2022-10-20-22_10_35.db"
  model_name: "xgboost"
  model_difference_threshold: 0.02
  model_class: "xgboost"
  data_path: "reduced"

calibrate_model:
  model_input_path: "resources/models/serialized/xgboost.pkl"
  data_path: "reduced"
  model_output_path: resources/models/serialized/xgboost_calibrated.pkl
  calibration_method: "isotonic"