paths:
  data:
    raw: "resources/data/raw"
    splitted: "resources/data/splitted"
    clean: "resources/data/clean"
    transformed_numerical_columns: "resources/data/transformed_numerical_columns"
    balanced: "resources/data/balanced"
    transformed_categorical_columns: "resources/data/categorical_transformed"
    reduced: "resources/data/reduced"
  pipelines:
    serialized: "resources/pipelines/serialized"
  models:
    serialized: "resources/models/serialized"
    parameters: "resources/models/parameters"
    optuna_studies: "resources/models/studies"

split_data:
  random_state: 42
  test_size: 0.15
  valid_size: 0.15

balance_data:
  method: "oversample"

transform_categorical_columns:
  method: "one_hot"


category_embedding:
  embedder_n_epochs: 5
  embedder_num_layers: 2

reduce_data:
  method: "rfe"

frufs:
  output_n_cols: 200

rfe:
  output_n_cols: 200