preprocessing_paths:
  - "resources/preprocessing/serialized/data_cleaner.pkl"
  - "resources/preprocessing/serialized/numerical_columns_transformer.pkl"
  - "resources/preprocessing/serialized/categorical_columns_transformer.pkl"
  - "resources/preprocessing/serialized/data_reductor.pkl"

model_path: "resources/models/serialized/xgboost_calibrated.pkl"